Repository HROKA/food-delivery-react-native, pull requests merged in 2020-09, with the labels that each got.

#5 Config Eslint and install npm modules
  .eslintrc.js
  .vscode/settings.json
  App.js
  app.json
  babel.config.js
  package-lock.json
  package.json
Labels: awaiting review, enhancement, file structure

#10 Add Local host as default Proxy [Developer-Mod]
  .eslintrc.js
  Utils/apiRequest.js
  Utils/fetchData.js
  package.json
Labels: Done, api request, awaiting review

#13 Image-card main component
  .eslintrc.js
  components/ImageCard/Image.js
  components/ImageCard/index.js
  components/ImageCard/style.js
  style.js
Labels: awaiting review, componemt

#14 Text Input [Component]
  components/TextInput/index.js
  components/TextInput/style.js
  package-lock.json
  package.json
Labels: awaiting review

#16 Create Button component
  .eslintrc.js
  components/Button/index.js
  components/Button/style.js
  style.js
Labels: awaiting review, react-component

#20 added screens and routes
  App.js
  package-lock.json
  package.json
  screens/Favorites/index.js
  screens/Favorites/style.js
  screens/Home/index.js
  screens/Home/style.js
  screens/Orders/index.js
  screens/Orders/style.js
  screens/Profile/index.js
  screens/Profile/style.js
  screens/Search/index.js
  screens/Search/style.js
Labels: awaiting review

#22 added constants file
  Utils/Constants.js
  components/Button/style.js
  components/ImageCard/style.js
  components/TextInput/style.js
  style.js
Labels: awaiting review

#23 Bottom tab bar
  App.js
  components/BottomTabBar/icons/Favorites.js
  components/BottomTabBar/icons/Home.js
  components/BottomTabBar/icons/Orders.js
  components/BottomTabBar/icons/Profile.js
  components/BottomTabBar/icons/Search.js
  components/BottomTabBar/index.js
  components/BottomTabBar/style.js
  package-lock.json
  package.json
Labels: Done, componemt

#17 Login Screen [Screens]
  .eslintrc.js
  App.js
  Utils/Constants.js
  Utils/apiRequest.js
  Utils/fetchData.js
  Utils/secureStorage.js
  app.json
  assets/background.png
  assets/header.png
  assets/logo.png
  components/Button/index.js
  components/TextInput/index.js
  components/TextInput/style.js
  package-lock.json
  package.json
  screens/signIn/FacebookLogin.js
  screens/signIn/index.js
  screens/signIn/style.js
Labels: inprogres, screen

#24 SignUp Screen
  App.js
  components/Picker/index.js
  components/Picker/style.js
  package.json
  screens/SignUp/index.js
  screens/SignUp/style.js
Labels: api request, awaiting review, componemt

#26 Update app and React Native Router
  App.js
  Utils/fetchData.js
  Utils/secureStorage.js
  components/BottomTabBar/index.js
  package-lock.json
  screens/Home/index.js
  screens/Profile/index.js
  screens/SignUp/index.js
  screens/Welcome/index.js
  screens/Welcome/style.js
  screens/signIn/FacebookLogin.js
  screens/signIn/index.js
Labels: api request, awaiting review, react-component, screen
